---

- name: install LXC packages
  apt: name={{ item }} state=present force=yes
  tags: lxc
  with_items:
    - lxc
    - bridge-utils
    - debootstrap
    - git
    - git-core
    - dnsmasq
    - dnsmasq-utils
    - kexec-tools
    - cgroupfs-mount

- name: install latest kernel image from backports
  apt: name=linux-image-amd64 state=latest default_release=wheezy-backports force=yes
  when: ansible_distribution_release == 'wheezy'

- stat: path=/usr/share/lxc/templates/lxc-debian-wheezy
  register: lxc_template_absent
  when: ansible_distribution_release == 'wheezy'

- name: copy better squeeze template
  copy: src=lxc-debian-0.9.0-upstream-squeeze dest=/usr/share/lxc/templates/lxc-debian-squeeze owner=root group=root mode=0755
  when: lxc_template_absent|success and ansible_distribution_release == 'wheezy'

- name: copy better wheezy template
  copy: src=lxc-debian-0.9.0-upstream-wheezy dest=/usr/share/lxc/templates/lxc-debian-wheezy owner=root group=root mode=0755
  when: lxc_template_absent|success and ansible_distribution_release == 'wheezy'

- name: enable memory cgroup in GRUB
  lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX_DEFAULT' line='GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory swapaccount=1"' backup=yes
  notify: update grub

- name: mount cgroup sysfs
  mount: src=cgroup name='/sys/fs/cgroup' opts=defaults fstype=cgroup state=mounted

- name: create interfaces.d if not exist
  file: path=/etc/network/interfaces.d/ owner=root group=root mode=0755 state=directory

- name: configure network interfaces (NAT mode)
  template: src=interfaces_nat.j2 dest=/etc/network/interfaces.d/lxc
  when: lxc_network_mode == 'nat'

- name: configure network interfaces (BRIDGE mode)
  template: src=interfaces_bridge.j2 dest=/etc/network/interfaces backup=yes
  when: lxc_network_mode == 'bridge'

- name: configure dnsmasq
  template: src=dnsmasq.lxc.conf.j2 dest=/etc/dnsmasq.d/lxc.conf owner=root group=root mode=0644
  register: dnsmasq

- name: restart dnsmasq
  service: name=dnsmasq state=restarted
  when: dnsmasq.changed

- name: configure lxcbr0 dnsmasq
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.lxcbr0.conf owner=root group=root mode=0644
  when: lxc_tight_dedicated_dnsmasq

- name: add LXC template with network
  template: src=lxc-template.conf.j2 dest=/etc/lxc/lxc-template.conf owner=root group=root mode=0644

- name: start lxcbr0
  when: lxc_network_mode in ('nat', 'bridge')
  shell: ifup lxcbr0

- name: add lxc-convert
  copy: src=lxc-convert dest=/usr/bin/lxc-convert owner=root group=root mode=0755

- name: add lxc-resources-stats
  copy: src=lxc-resources-stats dest=/usr/bin/lxc-resources-stats owner=root group=root mode=0755
